export const TextTheme = {
  '2XL': {
    fontSize: '40px',
    fontKerning: '0px',
    letterSpacing: '0px',
    fontWeight: 'regular',
    cursor: 'default',
    caretColor: 'transparent',
  },
  XL: {
    fontSize: '20px',
    fontKerning: '0px',
    letterSpacing: '0px',
    fontWeight: 'regular',
    cursor: 'default',
    caretColor: 'transparent',
  },
  lg: {
    fontSize: '16px',
    fontKerning: '-10px',
    letterSpacing: '-0.16px',
    fontWeight: 'medium',
    cursor: 'default',
    caretColor: 'transparent',
  },
  md: {
    fontSize: '14px',
    fontKerning: '-0px',
    letterSpacing: '0px',
    fontWeight: 'regular',
    cursor: 'default',
    caretColor: 'transparent',
  },
  sm: {
    fontSize: '12px',
    fontKerning: '0px',
    letterSpacing: '0px',
    fontWeight: 'medium',
    cursor: 'default',
    caretColor: 'transparent',
  },
  xs: {
    fontSize: '10px',
    fontKerning: '0px',
    letterSpacing: '0px',
    fontWeight: 'medium',
    cursor: 'default',
    caretColor: 'transparent',
  },
};
